services:
  payara:
    image: payara/server-web:6.2025.6-jdk17
    ports:
      - '8080:8080'
      - '4848:4848'
    volumes:
      - ./target/users-api.war:/opt/payara/deployments/users-api.war
    environment:
      - PAYARA_ARGS=--debug